sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifiations:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@2.15.12
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release